name: Update Daily Chart

on:
  schedule:
    - cron: '45 13 * * *' # Runs daily at 2:00 PM UTC (adjust as needed)
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.3'
          use-public-rspm: true

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        # IMPORTANT: Make sure DT, htmlwidgets, gargle, httr, etc.,
        # are listed in your DESCRIPTION file so they get installed.

      - name: Run R script
        env:
          # Your old secrets (if still needed)
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          # The new secret for Google Fitness
          GOOGLE_FITNESS_TOKEN: ${{ secrets.GOOGLE_FITNESS_TOKEN }} # <-- ADD THIS
        run: Rscript create_plot.R # This should be your combined R script

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # This will now correctly find and upload your generated HTML
          path: './docs'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
